### ISSUE TITLE
Configuration 'compile' 

### ISSUE THREAD

**Issue by pygabo** [MokoBeaconX/mokoBeaconX_Android#1]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by liuwenzheng** [comment]
Yes, I know this problem, because the version of Android Studio we use is below 3.0, and the version above 3.0 uses a new configuration. You can manually modify compile to implementation, and we will fix this in the next release.

**Comment by pygabo** [comment]
When is the next update?

**Comment by pygabo** [comment]
` implementation project(path: ':mokosupport')`
error :
`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :mokosupport.`

**Comment by liuwenzheng** [comment]
We have fixed it, you can update it and try it out.

**Comment by pygabo** [comment]
Gracias les esta perfecto :+1:
