### ISSUE TITLE
measure power(txPower) is missing

### ISSUE THREAD

**Issue by Miteshmakwana73** [MokoBeaconX/mokoBeaconX_Android#10]
i am trying to get distance between beacon and device to get result i required txPower which i dont find in  scan response so is ther something missing in library? 
```

[
  {
    "mac": "F2:EE:97:63:1B:B6",
    "validDataHashMap": {
      "20": {
        "data": "20000bc819c0002f33f8009d2f9b",
        "type": 2
      }
    },
    "rssi": -67
  },
  {
    "mac": "D3:B9:AF:E1:D7:D3",
    "name": "BeaconX",
    "validDataHashMap": {
      "0afcd3b9afe1d7d3220164426561636f6e58": {
        "data": "0afcd3b9afe1d7d3220164426561636f6e58",
        "type": 4
      },
      "20": {
        "data": "20000bd21ac0002e83d8009ae51c",
        "type": 2
      }
    },
    "rssi": -56
  },
  {
    "mac": "C4:7D:65:69:95:B7",
    "validDataHashMap": {
      "1000016d6f6b6f736d61727400": {
        "data": "1000016d6f6b6f736d61727400",
        "type": 1
      }
    },
    "rssi": -57
  }
]
```

i am not getting txPower(measure power) in response so how can i get distance

**Comment by liuwenzheng** [comment]
TxPower can be obtained by using the method in 'BeaconXParser' class. You can refer to 'BeaconXListAdapter' for specific methods.

**Comment by Miteshmakwana73** [comment]
@liuwenzheng this one ?

```
int txPower = Integer.parseInt(data.substring(2, 4), 16);
device.txPower = (byte) txPower + "";
```
and data is "1000016d6f6b6f736d61727400" this

**Comment by liuwenzheng** [comment]
yes

**Comment by Miteshmakwana73** [comment]
@liuwenzheng why txpower is converting to byte because int txpower value is 252 and after converting to byte it's -4 so is this value is right? 

`device.txPower = (byte) txPower + "";`

**Comment by Miteshmakwana73** [comment]
@liuwenzheng and there are multiple validDataHashMap child


```
"validDataHashMap": {
      "0afcd3b9afe1d7d3220164426561636f6e58": {
        "data": "0afcd3b9afe1d7d3220164426561636f6e58",
        "type": 4
      },
      "20": {
        "data": "20000bd21ac0002e83d8009ae51c",
        "type": 2
      }
    },
    "rssi": -56
  },
```

 which data value i have to use to get txPower

**Comment by liuwenzheng** [comment]
> @liuwenzheng why txpower is converting to byte because int txpower value is 252 and after converting to byte it's -4 so is this value is right?
> 
> `device.txPower = (byte) txPower + "";`

Right,The value range of txPower is -40、-20、-16、-12、-8、-4、0、3、4


> @liuwenzheng and there are multiple validDataHashMap child
> 
> ```
> "validDataHashMap": {
>       "0afcd3b9afe1d7d3220164426561636f6e58": {
>         "data": "0afcd3b9afe1d7d3220164426561636f6e58",
>         "type": 4
>       },
>       "20": {
>         "data": "20000bd21ac0002e83d8009ae51c",
>         "type": 2
>       }
>     },
>     "rssi": -56
>   },
> ```
> 
> which data value i have to use to get txPower

if the type is 4,you can uses the `BeaconXParser.getDevice(validData.data)` get the txPower;
if the type is 2,that means the data is TLM,there is no txPower

**Comment by Miteshmakwana73** [comment]
@liuwenzheng thank you for the brief details, so only type 4 is only valid for txPower other type means no txPower right? ex. 1,0, or any other

**Comment by liuwenzheng** [comment]
No, only TLM(type 2) has no txPower, but all other types (see BeaconXParser for details)

**Comment by Miteshmakwana73** [comment]
@liuwenzheng in demo project 

```
 if (validData.type == BeaconXInfo.VALID_DATA_FRAME_TYPE_INFO) {
                BeaconXDevice beaconXDevice = BeaconXParser.getDevice(validData.data); }
```
getDevice method used only if the type is 4

in getDevice method all the txPower logic is written

**Comment by liuwenzheng** [comment]
If you want the distance, you need the RSSI@1m value for the iBeacon frame, which is of type 3,uses`BeaconXParser.getiBeacon(validData.data)`

**Comment by Miteshmakwana73** [comment]
not getting type 3 in value in any hashmap value

**Comment by liuwenzheng** [comment]
Once you have connected the device, set one of the SLOT to be iBeacon

**Comment by Miteshmakwana73** [comment]
what happen if i calculate distance on the value of type 4 txPower do i get wrong distance?

**Comment by liuwenzheng** [comment]
Sorry, we haven't tested it

**Comment by Miteshmakwana73** [comment]
@liuwenzheng thank you for your response but it's too complicated to work according to type and I didn't understand much. I only understand is type 4 is good for getting txPower

so i'll perform calculation according to txPower and rssi

**Comment by Miteshmakwana73** [comment]
@liuwenzheng i am using this to get distance is it the right solution?

    Math.pow(10.0, ((txPower - this) / (10 * 2)).toDouble()))

**Comment by liuwenzheng** [comment]
```
Math.pow(10.0, ((rssi -  txPower) / (10 * 2)).toDouble()))
```
RSSI and txPwer need to take absolute values, using `Math.abs()`.

**Comment by Miteshmakwana73** [comment]
`Math.pow(10.0, ((Math.abs(rssi) - Math.abs(txPower)) / (10 * 2)).toDouble())`

@liuwenzheng this is right?

**Comment by liuwenzheng** [comment]
yes

**Comment by Miteshmakwana73** [comment]
@liuwenzheng hello what is Measured Power value? of beacons
