### ISSUE TITLE
after updating sdk demo project not getting beacons list in android 10

### ISSUE THREAD

**Issue by Miteshmakwana73** [MokoBeaconX/mokoBeaconX_Android#9]
hello I downloaded your source code and my requirement to run in SDK level 30 so I first migrated the project to AndroidX and run in android 10 it's working the same as before 

 ```
compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.moko.beaconx"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode 8
        versionName "2.1.5"
```

working fine in android 10 while using this configuration

```
 compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.moko.beaconx"
        minSdkVersion 18
        targetSdkVersion 30
        versionCode 8
        versionName "2.1.5"
```

not getting device list in android 10 after upgrading sdk 

also not getting device list `buildToolsVersion "29.0.3"` sdk `29`

even I also created a sample demo [project ](https://github.com/Miteshmakwana73/MokoDemo)but because of SDK 30 it's not getting beacons list and my other question is how can I get the distance between me and beacons in ft.

Please check this issue any help would be highly appreciated

**Comment by liuwenzheng** [comment]
Thanks for the feedback, we have updated the SDK, and the problem you reported has been solved

**Comment by Miteshmakwana73** [comment]
@liuwenzheng thank you for your response, I also mention in the description how do I get the distance? I don't know what and how do I get distance and couldn't find anything related to get the distance in documents

please suggest me

**Comment by liuwenzheng** [comment]
Sorry, we do not currently support this feature

**Comment by Miteshmakwana73** [comment]
thank you for your response

**Comment by Miteshmakwana73** [comment]
hello @liuwenzheng I found the getDistance function in MokoUtils

```
 public static double getDistance(int rssi, int acc) {
        int iRssi = Math.abs(rssi);
        double power = (iRssi - acc) / (10 * n_Value);
        return Math.pow(10, power);
    }
```

what does this function do?

**Comment by liuwenzheng** [comment]
This method is not used because the device is currently missing a key value acc

**Comment by Miteshmakwana73** [comment]
okay got it so the distance feature is not supported by library
